{% set name = "arcjetCV" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/magnus-haw/arcjetCV/archive/refs/tags/v{{ version }}.tar.gz
  sha256: feb62e8c3d228f15008925b5dbf59c9617408056b0059ceeff2bb88497d5f9b1

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - pip
    - setuptools
    - python
    - numpy
    - qt-main
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pytorch
    - pyside6
    - opencv
    - matplotlib-base
    - pandas
    - pyarrow
    - scikit-learn
    - segmentation-models-pytorch
    - torchvision
    - ocl-icd-system  # [linux]

test:
  imports:
    - arcjetCV
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/magnus-haw/arcjetCV/
  summary: 'App to process arcjet videos and segment the edge of the shock and of the sample.'
  description: |
    App to process arcjet videos and segment the edge of the shock and of the sample.

  license: NASA-1.3
  license_file: LICENSE
  doc_url: https://arcjetcv.readthedocs.io/
  dev_url: https://github.com/magnus-haw/arcjetCV/

extra:
  recipe-maintainers:
    - alexandrequ
    - magnus-haw
    - fedesemeraro
    - alexandrequ
